axon:
  server:
    addresses: ${AXON_SERVER_ADDRESSES:axonserver:8124}
  eventhandling:
    processors:
      kafkaProcessor:
        source: kafkaMessageSource

axon.kafka:
  client-id: saga-service
  default-topic: axon-events
  bootstrap-servers: localhost:9092
  consumer:
    group-id: saga-consumers
